### PR TITLE
Temporarily fix the problem of baranserver domain

### PR DESCRIPTION
**Pull request by fransua**

### CODE REVIEW

**Comment by Poshi** [comment]
What happened? The server is no longer available?

**Comment by fransua** [comment]
I think nobody paid for the domain... :S

**Comment by emi80** [comment]
The domain ``barnaserver.com`` was not working in December but should be back up now. It is working for me. Your change in the code seem more a DNS issue. Are you behind a firewall or working through VPN?

**Comment by fransua** [comment]
Ok, sorry I should have checked before...
it work for me too now.

On 12 January 2016 at 12:49, Emilio Palumbo <notifications@github.com>
wrote:

> The domain barnaserver.com was not working in December but should be back
> up now. It is working for me. Your change in the code seem more a DNS
> issue. Are you behind a firewall or working through VPN?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gemtools/gemtools/pull/20#issuecomment-170887392>.
>



-- 

*François Serra *
**Postdoctoral Fellow**

*Structural Genomics Tea**m - CNAG *- Centre Nacional d’Anàlisi Genòmica
*Structural Genomics Group - CRG *- Centre de Regulació Genòmica
Parc Científic de Barcelona – Torre I
Baldiri Reixac, 4
08028 Barcelona
Tel: +34 934 020 828

**Comment by emi80** [comment]
Good! No problem at all.

Cheers!

**Comment by Poshi** [comment]
Hummm... rollback of the change?


--
Jordi Camps
jcamps@gmail.com

-----BEGIN GEEK CODE BLOCK-----
Version: 3.12
GCS/IT/S d-(+) s: a C++ UL++++() P+ L+(++) E- W++ N o? K? w++ !O M V
PS++ PE- Y? PGP t 5 X R(+) tv(+) b+ DI+ D+ G e+++ h r(--) y+**
------END GEEK CODE BLOCK------

2016-01-12 13:34 GMT+01:00 Emilio Palumbo <notifications@github.com>:

**Comment by fransua** [comment]
yes....

On 12 January 2016 at 13:46, Jordi <notifications@github.com> wrote:

> Hummm... rollback of the change?
>
>
> --
> Jordi Camps
> jcamps@gmail.com
>
> -----BEGIN GEEK CODE BLOCK-----
> Version: 3.12
> GCS/IT/S d-(+) s: a C++ UL++++() P+ L+(++) E- W++ N o? K? w++ !O M V
> PS++ PE- Y? PGP t 5 X R(+) tv(+) b+ DI+ D+ G e+++ h r(--) y+**
> ------END GEEK CODE BLOCK------
>
> 2016-01-12 13:34 GMT+01:00 Emilio Palumbo <notifications@github.com>:
>
> > Good! No problem at all.
> >
> > Cheers!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/gemtools/gemtools/pull/20#issuecomment-170898191>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gemtools/gemtools/pull/20#issuecomment-170901228>.
>



-- 

*François Serra *
**Postdoctoral Fellow**

*Structural Genomics Tea**m - CNAG *- Centre Nacional d’Anàlisi Genòmica
*Structural Genomics Group - CRG *- Centre de Regulació Genòmica
Parc Científic de Barcelona – Torre I
Baldiri Reixac, 4
08028 Barcelona
Tel: +34 934 020 828

**Pull request merged**
